cloudnative-pg/postgres-containers

Debian/update.sh

Closes #14 
Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@enterprisedb.com>

chore: Increase the size of the search for images

---

.github/workflows/build.yml

Closes #25 
Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@enterprisedb.com>

fix: add missing `accept-keywords` to dockle-scan action

---

Debian/update.sh

Signed-off-by: Niccolò Fei <niccolo.fei@enterprisedb.com>

chore: unpin google-api-core

---

Debian/15/Dockerfile
Debian/update.sh

Increasing the condition will consider as beta any version after 15
Closes #37
Signed-off-by: Jonathan Gonzalez V <jonathan.abdiel@gmail.com>

chore: beta version now are greater than 15

---

.github/generate-strategy.sh
Debian/Dockerfile.template
Debian/update.sh

Signed-off-by: Niccolò Fei <niccolo.fei@enterprisedb.com>

chore: set v15 as the latest tag

---

.github/generate-strategy.sh
.github/workflows/build.yml
.github/workflows/update.yml

Signed-off-by: Niccolò Fei <niccolo.fei@enterprisedb.com>

chore: replace deprecated set-output command

---

Debian/Dockerfile.template

Added the org.opencontainers.image.description label with the proper description.
Closes #45
Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@enterprisedb.com>

chore: add org.opencontainers.image.description label

---

Debian/Dockerfile.template
README.md

feat: add Postgres Failover Slots extension to images

---

Debian/Dockerfile-beta.template

Closes cloudnative-pg/cloudnative-pg#2279

chore: add PgAudit to PG 16 beta image

---

Debian/Dockerfile-beta.template
Debian/Dockerfile.template
README.md

feat: add `pgvector` extension

---

.github/workflows/update.yml

closes: https://github.com/cloudnative-pg/cloudnative-pg/issues/3594

fix: match python version in update workflow to the container content

---

.github/generate-strategy.sh
.github/workflows/build.yml

feat: generate a ClusterImageCatalog on image update

---

lib/repo_funcs.sh

This reverts commit aaa363875255b6e40984bf56b9857dd4b3180aee.

Revert "fix: set a fixed version of Barman to 3.11.1 (#119)"

---

.github/workflows/update.yml
README.md

ci: run the update workflow every Mon

---

renovate.json

Allow renovate to update the GitHub workflows.

chore: add github actions to renovate config

---

docker-bake.hcl

closes #149
Signed-off-by: Daniel Chambre <smiyc@pm.me>

fix missing "$"

---

lib/repo_funcs.sh

Same as https://github.com/cloudnative-pg/plugin-barman-cloud/issues/127 but for system images.
Related to https://github.com/cloudnative-pg/cloudnative-pg/issues/5758

feat: support additional barman-cloud compression methods in system images

---

lib/repo_funcs.sh

chore: update barman-cloud to version 3.13.3

---

lib/repo_funcs.sh

This will avoid having old dependencies with vulnerabilities
Closes #238

chore: update requirements.txt file with latest versions

---

.github/workflows/bake_update.yml
docker-bake.hcl

Automatically update PostgreSQL versions in the Bake file,
this will get the information from the official site of PostgreSQL.
Closes #153

chore: automatically update available PostgreSQL versions

---

.github/workflows/bake.yml

Adjust the regexp to support preview versions and avoid duplicates in bake.yml.

ci: support preview versions in bake.yaml

---

.github/workflows/bake.yml
.github/workflows/bake_targets.yml

ci: fix snyk security scans in bake_targets.yml
